# .github/workflows/ci.yml
name: Build and Run Spring Project

on:
  push:
    branches:
      - master # Chạy khi có thay đổi trên nhánh master
  pull_request:
    branches:
      - master

jobs:
  build_and_run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Sử dụng JDK 11
          distribution: 'temurin'
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Run Application
        run: mvn spring-boot:run