# .github/workflows/ci.yml
name: Build and Run Spring Project

on:
  push:
    branches:
      - master # Chạy khi có thay đổi trên nhánh master
  pull_request:
    branches:
      - master

jobs:
  build_and_run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Sử dụng JDK 11
          distribution: 'temurin'
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

#      - name: Run Application
#        run: mvn spring-boot:run
      - name: Stop Existing Application
        run: |
          # Dừng tiến trình cũ nếu đang chạy trên cổng 8083
          PID=$(lsof -ti:8083 || true)
          if [ ! -z "$PID" ]; then
            echo "Dừng tiến trình cũ với PID $PID"
            kill -9 $PID
          fi
          
          # Khởi động ứng dụng mới ở chế độ nền

      - name: Run Application
        run: nohup java -jar target/SimpleSpring-0.0.1-SNAPSHOT.jar > app.log 2>&1 &